---
- name: Setup monitoring stack
  hosts: all
  become: true

  pre_tasks:
    - name: Ensure pip is installed on Debian-based systems
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure pip is installed on Red Hat-based systems
      ansible.builtin.yum:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat"
    - name: Ensure kubernetes Python library is installed
      ansible.builtin.pip:
        name: kubernetes
        state: present
      become: true
    - name: Ensure monitoring namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: monitoring
        state: present

  roles:
    - kube-facts
    - helm
    - prometheus
    
