---
- name: Create custom values file for Prometheus stack
  ansible.builtin.copy:
    dest: /tmp/custom_kube_prometheus_stack.yml
    content: |
      alertmanager:
        alertmanagerSpec:
          # Selects Alertmanager configuration based on these labels.
          # Ensure that the Alertmanager configuration has matching labels.
          alertmanagerConfigSelector:
            matchLabels:
              release: monitoring

          # Sets the number of Alertmanager replicas to 3 for high availability.
          # Use 2 or more replicas for resilience.
          replicas: 2

          # Sets the strategy for matching Alertmanager configurations.
          # 'None' means no specific matching strategy.
          alertmanagerConfigMatcherStrategy:
            type: None


- name: Add Prometheus community repo
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  register: add_repo
  failed_when: false

- name: Update Helm repositories
  command: helm repo update
  when: add_repo.changed

- name: Check if Prometheus is installed
  command: helm status prometheus -n monitoring
  register: prometheus_check
  failed_when: false

- name: Install Prometheus stack using custom values
  command: helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f /tmp/custom_kube_prometheus_stack.yml
  when: prometheus_check.rc != 0

- name: Expose Grafana with NodePort
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana-public
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: grafana
        ports:
          - port: 80
            targetPort: 3000
            nodePort: 32000  # Adjust if needed
            protocol: TCP

- name: Expose Prometheus with NodePort
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: prometheus-public
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: prometheus
        ports:
          - port: 9090
            targetPort: 9090
            nodePort: 32001  # Adjust if needed
            protocol: TCP

- name: Expose Alertmanager with NodePort
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: alertmanager-public
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: alertmanager
        ports:
          - port: 9093
            targetPort: 9093
            nodePort: 32002  # Adjust if needed
            protocol: TCP

- name: Display access URLs
  debug:
    msg: |
      Grafana: http://<node-ip>:32000
      Prometheus: http://<node-ip>:32001
      Alertmanager: http://<node-ip>:32002
